"""empty message

Revision ID: 59db749b4f3b
Revises: cd8e82d4fbde
Create Date: 2021-02-16 01:17:49.121912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59db749b4f3b'
down_revision = 'cd8e82d4fbde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
